[package]
name = "lockfree_car"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = {version="0.8.4", default-features=false, features=["crossbeam-queue", "crossbeam-epoch", "alloc"]}
crossbeam-skiplist = "*"
thread_local = "1.1.8"
